
server:
   port: 8111
spring:
   application:  
      name: zuulserver
zuul:
  routes:
   products:
      path: /api/demo/**
      url: http://localhost:8080/
 #to run this start SpringBootRestExampleDemo project 
 #hit url like localhost:8111/api/demo/products