server:
      port: 8081
spring:
    application:
      name: Simple Application name

#---
#spring:
#  profiles: dev
#   application:
 #     name: demoservice
#server:
 #  port: 9090

#---
#spring: 
#   profiles: prod
#   application:
#      name: demoservice
#server: 
#   port: 4431